[tool.poetry]
name = "configu-sdk"
version = "0.1.0"
description = ""
authors = ["Or Levi <orlevi128@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
packages = [
  { include = "configu", from = "src" },
]

[tool.poetry.dependencies]
python = ">=3.7,<4.0"
jinja2 = "^3.1.2"
requests = "^2.28.1"
py-validator = "^0.17.0"
pydantic = "^1.10.6"


[tool.poetry.group.dev.dependencies]
black = "^22.12.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
