[context.production.environment]
  CONFIGU_SET = "production"

[context.deploy-preview.environment]
  CONFIGU_SET = "staging/preview"

[context.branch-deploy.environment]
  CONFIGU_SET = "staging/branch"
