name: "CD: configu pypi package"

on:
  push:
    tags:
      - py-*

env:
  PACKAGE_NAME: "configu"

jobs:
  build_and_deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/deploy-start-action
        id: deployment
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: ./.github/actions/ts-env-action
      - uses: ./.github/actions/py-env-action
        with:
          token: ${{ secrets.PY_TOKEN }}
      # ----------
      - name: Bump package version
        run: |
          cd ${{ env.CWD }}
          poetry version ${{ steps.deployment.outputs.release-version }}

      - name: Build package code
        run: |
          cd ${{ env.CWD }}
          poetry build

      - name: Publish to pypi
        run: |
          cd ${{ env.CWD }}
          poetry publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # ----------

      - uses: ./.github/actions/deploy-end-action
        if: always()
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          package-version: ${{ steps.deployment.outputs.release-version }}
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
