name: "CI: repository healthcare routines"

on:
  pull_request:
    branches:
      - main

jobs:
  run_healthcare_routines_on_code_changes:
    name: Run repository healthcare routines on code changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker # https://github.com/marketplace/actions/lychee-broken-link-checker
        uses: lycheeverse/lychee-action@v1.6.1
        with:
          fail: true
