name: "CI Python Tests"
on:
  pull_request:
    branches:
      - main
    paths:
      - "py/**"

jobs:
  ci:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/py-env-action
      - name: Run Tests
        run: cd ${{ env.CWD }} && poetry run pytest
